name: branch

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run tests and check build on latest ubuntu and python version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pytest --exitfirst --verbose --failed-first
    - name: Install build dependencies and build tools
      run: python setup.py sdist bdist_wheel
    - name: Checking distribution
      run: twine check dist/*
